### ISSUE TITLE
Add example using sleep mode of BLE

### ISSUE THREAD

**Issue by Sebichev** [Seeed-Studio/Seeed_Arduino_MG126#2]
I would like to set my BLE into sleep mode to save battery lifetime. Then BLE would periodicaly wake up or at my request. 

Could you provide an example where sleeping mode / wake up feature are used ?

**Comment by baorepo** [comment]
https://github.com/ee-quipment/ZeroPowerManager @Sebichev  This MG126 is just the RF front end of Bluetooth, if you need sleep function, you can use the code of samd.
